//! Rust Axum code generation
//!
//! Generates server-side Rust code for Axum framework from topo API definitions.

use crate::ast::{
    ApiServiceDef, BinaryOperator, Expression, HttpMethod, ObjectMember, ServerBlock,
    ServerHandler, ServerStatement, UnaryOperator,
};

/// Rust Axum code generator
pub struct AxumCodegen {
    output: String,
    indent: usize,
}

impl AxumCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    /// Generate Rust Axum code from API service definitions
    pub fn generate(&mut self, services: &[&ApiServiceDef]) -> String {
        self.output.clear();

        // Generate header and imports
        self.writeln("// Generated by topo - Rust Axum Server");
        self.writeln("// Do not edit manually");
        self.writeln("");
        self.writeln("use axum::{");
        self.indent += 1;
        self.writeln("extract::{Path, State, Json},");
        self.writeln("http::StatusCode,");
        self.writeln("response::IntoResponse,");
        self.writeln("routing::{get, post, put, patch, delete},");
        self.writeln("Router,");
        self.indent -= 1;
        self.writeln("};");
        self.writeln("use serde::{Deserialize, Serialize};");
        self.writeln("use std::sync::Arc;");
        self.writeln("");

        // Generate error types
        self.generate_error_types();

        // Generate AppState
        self.generate_app_state();

        // Generate handlers for each service
        for service in services {
            if let Some(server_block) = &service.server {
                self.generate_service_handlers(service, server_block);
            }
        }

        // Generate router function
        self.generate_router(services);

        // Generate main function
        self.generate_main();

        self.output.clone()
    }

    fn generate_error_types(&mut self) {
        self.writeln("// Error types");
        self.writeln("#[derive(Debug)]");
        self.writeln("pub enum ApiError {");
        self.indent += 1;
        self.writeln("NotFound(String),");
        self.writeln("BadRequest(String),");
        self.writeln("Unauthorized(String),");
        self.writeln("Forbidden(String),");
        self.writeln("Conflict(String),");
        self.writeln("Internal(String),");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");

        self.writeln("impl IntoResponse for ApiError {");
        self.indent += 1;
        self.writeln("fn into_response(self) -> axum::response::Response {");
        self.indent += 1;
        self.writeln("let (status, message) = match self {");
        self.indent += 1;
        self.writeln("ApiError::NotFound(msg) => (StatusCode::NOT_FOUND, msg),");
        self.writeln("ApiError::BadRequest(msg) => (StatusCode::BAD_REQUEST, msg),");
        self.writeln("ApiError::Unauthorized(msg) => (StatusCode::UNAUTHORIZED, msg),");
        self.writeln("ApiError::Forbidden(msg) => (StatusCode::FORBIDDEN, msg),");
        self.writeln("ApiError::Conflict(msg) => (StatusCode::CONFLICT, msg),");
        self.writeln("ApiError::Internal(msg) => (StatusCode::INTERNAL_SERVER_ERROR, msg),");
        self.indent -= 1;
        self.writeln("};");
        self.writeln("(status, Json(serde_json::json!({ \"error\": message }))).into_response()");
        self.indent -= 1;
        self.writeln("}");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn generate_app_state(&mut self) {
        self.writeln("// Application state");
        self.writeln("#[derive(Clone)]");
        self.writeln("pub struct AppState {");
        self.indent += 1;
        self.writeln("// Add your database pool and other shared state here");
        self.writeln("// pub db: sqlx::PgPool,");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn generate_service_handlers(&mut self, service: &ApiServiceDef, server_block: &ServerBlock) {
        let base_path = service.rest.as_deref().unwrap_or("");

        self.writeln(&format!("// Handlers for {} API", service.name));
        self.writeln("");

        for handler in &server_block.handlers {
            if let Some(endpoint) = service.endpoints.iter().find(|e| e.name == handler.endpoint) {
                let full_path = format!("{}{}", base_path, endpoint.path);
                self.generate_handler(handler, &full_path, &endpoint.method, &service.name);
                self.writeln("");
            }
        }
    }

    fn generate_handler(
        &mut self,
        handler: &ServerHandler,
        path: &str,
        method: &HttpMethod,
        service_name: &str,
    ) {
        let fn_name = self.to_snake_case(&format!("{}_{}", service_name, handler.endpoint));

        // Extract path parameters
        let path_params: Vec<&str> = path
            .split('/')
            .filter(|s| s.starts_with(':'))
            .map(|s| &s[1..])
            .collect();

        // Generate function signature
        self.write("pub async fn ");
        self.write(&fn_name);
        self.writeln("(");
        self.indent += 1;
        self.writeln("State(state): State<Arc<AppState>>,");

        // Add path parameters if any
        if !path_params.is_empty() {
            let params_type = if path_params.len() == 1 {
                "String".to_string()
            } else {
                format!("({})", vec!["String"; path_params.len()].join(", "))
            };
            self.writeln(&format!("Path({}): Path<{}>,", path_params.join(", "), params_type));
        }

        // Add request body for POST/PUT/PATCH
        if matches!(method, HttpMethod::Post | HttpMethod::Put | HttpMethod::Patch) {
            self.writeln("Json(body): Json<serde_json::Value>,");
        }

        self.indent -= 1;
        self.writeln(") -> Result<impl IntoResponse, ApiError> {");
        self.indent += 1;

        // Generate handler body
        for stmt in &handler.body {
            self.generate_statement(stmt);
        }

        self.indent -= 1;
        self.writeln("}");
    }

    fn generate_statement(&mut self, stmt: &ServerStatement) {
        match stmt {
            ServerStatement::Assignment { name, value } => {
                let expr_str = self.generate_expression(value);
                self.writeln(&format!("let {} = {};", name, expr_str));
            }
            ServerStatement::Return { value } => {
                let expr_str = self.generate_expression(value);
                self.writeln(&format!("Ok(Json({}))", expr_str));
            }
            ServerStatement::Throw { error_type, message } => {
                let msg_str = self.generate_expression(message);
                let error_variant = match error_type.as_str() {
                    "NotFoundError" => "NotFound",
                    "BadRequestError" => "BadRequest",
                    "UnauthorizedError" => "Unauthorized",
                    "ForbiddenError" => "Forbidden",
                    "ConflictError" => "Conflict",
                    _ => "Internal",
                };
                self.writeln(&format!(
                    "return Err(ApiError::{}({}.to_string()));",
                    error_variant, msg_str
                ));
            }
            ServerStatement::If {
                condition,
                then_block,
                else_block,
            } => {
                let cond_str = self.generate_expression(condition);
                self.writeln(&format!("if {} {{", cond_str));
                self.indent += 1;
                for s in then_block {
                    self.generate_statement(s);
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_block {
                    self.writeln("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.generate_statement(s);
                    }
                    self.indent -= 1;
                }
                self.writeln("}");
            }
            ServerStatement::TryCatch {
                try_block,
                catch_param,
                catch_block,
            } => {
                // In Rust, we use match with Result
                self.writeln("match (|| -> Result<_, ApiError> {");
                self.indent += 1;
                for s in try_block {
                    self.generate_statement(s);
                }
                self.writeln("Ok(())");
                self.indent -= 1;
                self.writeln("})() {");
                self.indent += 1;
                self.writeln("Ok(_) => {},");
                self.writeln(&format!("Err({}) => {{", catch_param));
                self.indent += 1;
                for s in catch_block {
                    self.generate_statement(s);
                }
                self.indent -= 1;
                self.writeln("}");
                self.indent -= 1;
                self.writeln("}");
            }
            ServerStatement::Expression(expr) => {
                let expr_str = self.generate_expression(expr);
                self.writeln(&format!("{};", expr_str));
            }
        }
    }

    fn generate_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::String { value } => format!("\"{}\"", value.replace('"', "\\\"")),
            Expression::Number { value } => {
                if value.fract() == 0.0 {
                    format!("{}", *value as i64)
                } else {
                    value.to_string()
                }
            }
            Expression::Boolean { value } => value.to_string(),
            Expression::Null => "None".to_string(),
            Expression::Identifier { name } => name.clone(),
            Expression::MemberAccess { object, property } => {
                format!("{}.{}", self.generate_expression(object), property)
            }
            Expression::Call { callee, args } => {
                let callee_str = self.generate_expression(callee);
                let args_str: Vec<String> = args.iter().map(|a| self.generate_expression(a)).collect();
                format!("{}({})", callee_str, args_str.join(", "))
            }
            Expression::Await { expr } => {
                format!("{}.await", self.generate_expression(expr))
            }
            Expression::BinaryOp { left, op, right } => {
                let op_str = match op {
                    BinaryOperator::Add => "+",
                    BinaryOperator::Sub => "-",
                    BinaryOperator::Mul => "*",
                    BinaryOperator::Div => "/",
                    BinaryOperator::Mod => "%",
                    BinaryOperator::Eq => "==",
                    BinaryOperator::Ne => "!=",
                    BinaryOperator::Lt => "<",
                    BinaryOperator::Le => "<=",
                    BinaryOperator::Gt => ">",
                    BinaryOperator::Ge => ">=",
                    BinaryOperator::And => "&&",
                    BinaryOperator::Or => "||",
                };
                format!(
                    "{} {} {}",
                    self.generate_expression(left),
                    op_str,
                    self.generate_expression(right)
                )
            }
            Expression::UnaryOp { op, operand } => {
                let op_str = match op {
                    UnaryOperator::Not => "!",
                    UnaryOperator::Neg => "-",
                };
                format!("{}{}", op_str, self.generate_expression(operand))
            }
            Expression::Object { members } => {
                let props: Vec<String> = members
                    .iter()
                    .filter_map(|m| {
                        if let ObjectMember::Property(prop) = m {
                            Some(format!("\"{}\": {}", prop.key, self.generate_expression(&prop.value)))
                        } else {
                            None
                        }
                    })
                    .collect();
                format!("serde_json::json!({{ {} }})", props.join(", "))
            }
            Expression::Array { elements } => {
                let elems: Vec<String> = elements.iter().map(|e| self.generate_expression(e)).collect();
                format!("vec![{}]", elems.join(", "))
            }
            Expression::SqlTemplate { parts, expressions } => {
                // Generate sqlx query
                // sql`SELECT * FROM users WHERE id = ${id}` -> sqlx::query!("SELECT * FROM users WHERE id = $1", id)
                let mut sql_str = String::new();
                let mut bindings = Vec::new();

                for (i, part) in parts.iter().enumerate() {
                    sql_str.push_str(part);
                    if i < expressions.len() {
                        sql_str.push_str(&format!("${}", i + 1)); // PostgreSQL style
                        bindings.push(self.generate_expression(&expressions[i]));
                    }
                }

                if bindings.is_empty() {
                    format!("sqlx::query!(\"{}\")", sql_str.replace('"', "\\\""))
                } else {
                    format!(
                        "sqlx::query!(\"{}\", {})",
                        sql_str.replace('"', "\\\""),
                        bindings.join(", ")
                    )
                }
            }
            _ => "/* unsupported expression */".to_string(),
        }
    }

    fn generate_router(&mut self, services: &[&ApiServiceDef]) {
        self.writeln("pub fn create_router(state: Arc<AppState>) -> Router {");
        self.indent += 1;
        self.writeln("Router::new()");
        self.indent += 1;

        for service in services {
            if let Some(server_block) = &service.server {
                let base_path = service.rest.as_deref().unwrap_or("");

                for handler in &server_block.handlers {
                    if let Some(endpoint) = service.endpoints.iter().find(|e| e.name == handler.endpoint) {
                        let full_path = format!("{}{}", base_path, endpoint.path);
                        let axum_path = full_path.replace(':', "");
                        let fn_name = self.to_snake_case(&format!("{}_{}", service.name, handler.endpoint));
                        let method_fn = match endpoint.method {
                            HttpMethod::Get => "get",
                            HttpMethod::Post => "post",
                            HttpMethod::Put => "put",
                            HttpMethod::Patch => "patch",
                            HttpMethod::Delete => "delete",
                        };
                        self.writeln(&format!(".route(\"{}\", {}({}))", axum_path, method_fn, fn_name));
                    }
                }
            }
        }

        self.writeln(".with_state(state)");
        self.indent -= 1;
        self.indent -= 1;
        self.writeln("}");
        self.writeln("");
    }

    fn generate_main(&mut self) {
        self.writeln("#[tokio::main]");
        self.writeln("async fn main() {");
        self.indent += 1;
        self.writeln("let state = Arc::new(AppState {});");
        self.writeln("");
        self.writeln("let app = create_router(state);");
        self.writeln("");
        self.writeln("let listener = tokio::net::TcpListener::bind(\"0.0.0.0:3000\")");
        self.indent += 1;
        self.writeln(".await");
        self.writeln(".expect(\"Failed to bind to port 3000\");");
        self.indent -= 1;
        self.writeln("");
        self.writeln("println!(\"Server running on http://localhost:3000\");");
        self.writeln("");
        self.writeln("axum::serve(listener, app)");
        self.indent += 1;
        self.writeln(".await");
        self.writeln(".expect(\"Server failed\");");
        self.indent -= 1;
        self.indent -= 1;
        self.writeln("}");
    }

    fn to_snake_case(&self, s: &str) -> String {
        let mut result = String::new();
        for (i, ch) in s.chars().enumerate() {
            if ch.is_uppercase() {
                if i > 0 {
                    result.push('_');
                }
                result.push(ch.to_ascii_lowercase());
            } else {
                result.push(ch);
            }
        }
        result
    }

    fn writeln(&mut self, line: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&indent_str);
        self.output.push_str(line);
        self.output.push('\n');
    }

    fn write(&mut self, text: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&indent_str);
        self.output.push_str(text);
    }
}

impl Default for AxumCodegen {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate Cargo.toml for Axum project
pub fn generate_cargo_toml(project_name: &str) -> String {
    format!(
        r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
"#,
        project_name
    )
}
