//! Cloudflare Workers JavaScript code generation
//!
//! Generates server-side JavaScript code for Cloudflare Workers from topo API definitions.

use crate::ast::{
    ApiServiceDef, BinaryOperator, Expression, HttpMethod, ObjectMember, ServerBlock,
    ServerHandler, ServerStatement, UnaryOperator,
};

/// Cloudflare Workers code generator
pub struct WorkersCodegen {
    output: String,
    indent: usize,
}

impl WorkersCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    /// Generate Cloudflare Workers code from API service definitions
    pub fn generate(&mut self, services: &[&ApiServiceDef]) -> String {
        self.output.clear();

        // Generate header
        self.writeln("// Generated by topo - Cloudflare Workers");
        self.writeln("// Do not edit manually");
        self.writeln("");

        // Generate main export
        self.writeln("export default {");
        self.indent += 1;
        self.writeln("async fetch(request, env, ctx) {");
        self.indent += 1;
        self.writeln("const url = new URL(request.url);");
        self.writeln("const method = request.method;");
        self.writeln("");

        // Generate route handlers
        for service in services {
            if let Some(server_block) = &service.server {
                self.generate_service_routes(service, server_block);
            }
        }

        // Generate 404 fallback
        self.writeln("");
        self.writeln("return new Response('Not Found', { status: 404 });");

        self.indent -= 1;
        self.writeln("}");
        self.indent -= 1;
        self.writeln("};");

        self.output.clone()
    }

    fn generate_service_routes(&mut self, service: &ApiServiceDef, server_block: &ServerBlock) {
        let base_path = service.rest.as_deref().unwrap_or("");

        for handler in &server_block.handlers {
            // Find matching endpoint
            if let Some(endpoint) = service.endpoints.iter().find(|e| e.name == handler.endpoint) {
                let full_path = format!("{}{}", base_path, endpoint.path);
                let method = match endpoint.method {
                    HttpMethod::Get => "GET",
                    HttpMethod::Post => "POST",
                    HttpMethod::Put => "PUT",
                    HttpMethod::Patch => "PATCH",
                    HttpMethod::Delete => "DELETE",
                };

                self.writeln(&format!("// {} {}", method, full_path));
                self.generate_route_handler(handler, &full_path, method);
                self.writeln("");
            }
        }
    }

    fn generate_route_handler(&mut self, handler: &ServerHandler, path: &str, method: &str) {
        // Generate path pattern matching
        let (pattern, param_names) = self.path_to_regex(path);

        self.writeln("{");
        self.indent += 1;

        self.writeln(&format!("const match = url.pathname.match({});", pattern));
        self.writeln(&format!("if (method === '{}' && match) {{", method));
        self.indent += 1;

        // Extract path parameters
        for (i, param) in param_names.iter().enumerate() {
            self.writeln(&format!("const {} = match[{}];", param, i + 1));
        }

        // Generate context object
        self.writeln("const context = { db: env.DB, kv: env.KV, env };");

        // Generate try-catch wrapper
        self.writeln("try {");
        self.indent += 1;

        // Generate handler body
        for stmt in &handler.body {
            self.generate_statement(stmt);
        }

        self.indent -= 1;
        self.writeln("} catch (error) {");
        self.indent += 1;
        self.writeln("if (error.status) {");
        self.indent += 1;
        self.writeln("return Response.json({ error: error.message }, { status: error.status });");
        self.indent -= 1;
        self.writeln("}");
        self.writeln("return Response.json({ error: 'Internal Server Error' }, { status: 500 });");
        self.indent -= 1;
        self.writeln("}");

        self.indent -= 1;
        self.writeln("}");
        self.indent -= 1;
        self.writeln("}");
    }

    fn generate_statement(&mut self, stmt: &ServerStatement) {
        match stmt {
            ServerStatement::Assignment { name, value } => {
                let expr_str = self.generate_expression(value);
                self.writeln(&format!("const {} = {};", name, expr_str));
            }
            ServerStatement::Return { value } => {
                let expr_str = self.generate_expression(value);
                self.writeln(&format!("return Response.json({});", expr_str));
            }
            ServerStatement::Throw { error_type, message } => {
                let msg_str = self.generate_expression(message);
                let status = match error_type.as_str() {
                    "NotFoundError" => 404,
                    "BadRequestError" => 400,
                    "UnauthorizedError" => 401,
                    "ForbiddenError" => 403,
                    "ConflictError" => 409,
                    _ => 500,
                };
                self.writeln(&format!(
                    "throw {{ status: {}, message: {} }};",
                    status, msg_str
                ));
            }
            ServerStatement::If {
                condition,
                then_block,
                else_block,
            } => {
                let cond_str = self.generate_expression(condition);
                self.writeln(&format!("if ({}) {{", cond_str));
                self.indent += 1;
                for s in then_block {
                    self.generate_statement(s);
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_block {
                    self.writeln("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.generate_statement(s);
                    }
                    self.indent -= 1;
                }
                self.writeln("}");
            }
            ServerStatement::TryCatch {
                try_block,
                catch_param,
                catch_block,
            } => {
                self.writeln("try {");
                self.indent += 1;
                for s in try_block {
                    self.generate_statement(s);
                }
                self.indent -= 1;
                self.writeln(&format!("}} catch ({}) {{", catch_param));
                self.indent += 1;
                for s in catch_block {
                    self.generate_statement(s);
                }
                self.indent -= 1;
                self.writeln("}");
            }
            ServerStatement::Expression(expr) => {
                let expr_str = self.generate_expression(expr);
                self.writeln(&format!("{};", expr_str));
            }
        }
    }

    fn generate_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::String { value } => format!("\"{}\"", value.replace('"', "\\\"")),
            Expression::Number { value } => value.to_string(),
            Expression::Boolean { value } => value.to_string(),
            Expression::Null => "null".to_string(),
            Expression::Identifier { name } => name.clone(),
            Expression::MemberAccess { object, property } => {
                format!("{}.{}", self.generate_expression(object), property)
            }
            Expression::Call { callee, args } => {
                let callee_str = self.generate_expression(callee);
                let args_str: Vec<String> = args.iter().map(|a| self.generate_expression(a)).collect();
                format!("{}({})", callee_str, args_str.join(", "))
            }
            Expression::Await { expr } => {
                format!("await {}", self.generate_expression(expr))
            }
            Expression::BinaryOp { left, op, right } => {
                let op_str = match op {
                    BinaryOperator::Add => "+",
                    BinaryOperator::Sub => "-",
                    BinaryOperator::Mul => "*",
                    BinaryOperator::Div => "/",
                    BinaryOperator::Mod => "%",
                    BinaryOperator::Eq => "===",
                    BinaryOperator::Ne => "!==",
                    BinaryOperator::Lt => "<",
                    BinaryOperator::Le => "<=",
                    BinaryOperator::Gt => ">",
                    BinaryOperator::Ge => ">=",
                    BinaryOperator::And => "&&",
                    BinaryOperator::Or => "||",
                };
                format!(
                    "{} {} {}",
                    self.generate_expression(left),
                    op_str,
                    self.generate_expression(right)
                )
            }
            Expression::UnaryOp { op, operand } => {
                let op_str = match op {
                    UnaryOperator::Not => "!",
                    UnaryOperator::Neg => "-",
                };
                format!("{}{}", op_str, self.generate_expression(operand))
            }
            Expression::Object { members } => {
                let props: Vec<String> = members
                    .iter()
                    .filter_map(|m| {
                        if let ObjectMember::Property(prop) = m {
                            Some(format!("{}: {}", prop.key, self.generate_expression(&prop.value)))
                        } else {
                            None
                        }
                    })
                    .collect();
                format!("{{ {} }}", props.join(", "))
            }
            Expression::Array { elements } => {
                let elems: Vec<String> = elements.iter().map(|e| self.generate_expression(e)).collect();
                format!("[{}]", elems.join(", "))
            }
            _ => "/* unsupported expression */".to_string(),
        }
    }

    /// Convert path template to regex pattern and extract parameter names
    fn path_to_regex(&self, path: &str) -> (String, Vec<String>) {
        let mut pattern = String::new();
        let mut params = Vec::new();
        let mut current = String::new();
        let mut in_param = false;

        for ch in path.chars() {
            if ch == ':' && !in_param {
                pattern.push_str(&regex::escape(&current));
                current.clear();
                in_param = true;
            } else if in_param && (ch == '/' || ch == '-') {
                params.push(current.clone());
                pattern.push_str("([^/]+)");
                current.clear();
                in_param = false;
                pattern.push(ch);
            } else {
                current.push(ch);
            }
        }

        if in_param {
            params.push(current);
            pattern.push_str("([^/]+)");
        } else if !current.is_empty() {
            pattern.push_str(&regex::escape(&current));
        }

        (format!("/^{}$/", pattern), params)
    }

    fn writeln(&mut self, line: &str) {
        let indent_str = "  ".repeat(self.indent);
        self.output.push_str(&indent_str);
        self.output.push_str(line);
        self.output.push('\n');
    }
}

impl Default for WorkersCodegen {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_path_to_regex() {
        let codegen = WorkersCodegen::new();

        let (pattern, params) = codegen.path_to_regex("/api/users/:id");
        assert_eq!(params, vec!["id"]);
        assert!(pattern.contains("([^/]+)"));

        let (pattern2, params2) = codegen.path_to_regex("/api/users/:userId/posts/:postId");
        assert_eq!(params2, vec!["userId", "postId"]);
        assert_eq!(pattern2.matches("([^/]+)").count(), 2);
    }
}
