use once_cell::sync::Lazy;

pub static TAILWIND_CLASSES: Lazy<Vec<(&'static str, &'static str)>> = Lazy::new(|| {
    vec![
        // Layout
        ("container", "Center and constrain content"),
        ("block", "Display: block"),
        ("inline-block", "Display: inline-block"),
        ("inline", "Display: inline"),
        ("flex", "Display: flex"),
        ("inline-flex", "Display: inline-flex"),
        ("grid", "Display: grid"),
        ("inline-grid", "Display: inline-grid"),
        ("hidden", "Display: none"),

        // Flexbox Direction
        ("flex-row", "Flex direction: row"),
        ("flex-row-reverse", "Flex direction: row-reverse"),
        ("flex-col", "Flex direction: column"),
        ("flex-col-reverse", "Flex direction: column-reverse"),

        // Flexbox Wrap
        ("flex-wrap", "Flex wrap: wrap"),
        ("flex-wrap-reverse", "Flex wrap: wrap-reverse"),
        ("flex-nowrap", "Flex wrap: nowrap"),

        // Flexbox Grow/Shrink
        ("flex-1", "Flex: 1 1 0%"),
        ("flex-auto", "Flex: 1 1 auto"),
        ("flex-initial", "Flex: 0 1 auto"),
        ("flex-none", "Flex: none"),
        ("grow", "Flex grow: 1"),
        ("grow-0", "Flex grow: 0"),
        ("shrink", "Flex shrink: 1"),
        ("shrink-0", "Flex shrink: 0"),

        // Justify Content
        ("justify-start", "Justify content: flex-start"),
        ("justify-end", "Justify content: flex-end"),
        ("justify-center", "Justify content: center"),
        ("justify-between", "Justify content: space-between"),
        ("justify-around", "Justify content: space-around"),
        ("justify-evenly", "Justify content: space-evenly"),

        // Align Items
        ("items-start", "Align items: flex-start"),
        ("items-end", "Align items: flex-end"),
        ("items-center", "Align items: center"),
        ("items-baseline", "Align items: baseline"),
        ("items-stretch", "Align items: stretch"),

        // Align Content
        ("content-start", "Align content: flex-start"),
        ("content-end", "Align content: flex-end"),
        ("content-center", "Align content: center"),
        ("content-between", "Align content: space-between"),
        ("content-around", "Align content: space-around"),
        ("content-evenly", "Align content: space-evenly"),

        // Gap
        ("gap-0", "Gap: 0"),
        ("gap-1", "Gap: 0.25rem"),
        ("gap-2", "Gap: 0.5rem"),
        ("gap-3", "Gap: 0.75rem"),
        ("gap-4", "Gap: 1rem"),
        ("gap-5", "Gap: 1.25rem"),
        ("gap-6", "Gap: 1.5rem"),
        ("gap-8", "Gap: 2rem"),
        ("gap-10", "Gap: 2.5rem"),
        ("gap-12", "Gap: 3rem"),
        ("gap-16", "Gap: 4rem"),
        ("gap-x-4", "Column gap: 1rem"),
        ("gap-y-4", "Row gap: 1rem"),

        // Grid
        ("grid-cols-1", "Grid: 1 column"),
        ("grid-cols-2", "Grid: 2 columns"),
        ("grid-cols-3", "Grid: 3 columns"),
        ("grid-cols-4", "Grid: 4 columns"),
        ("grid-cols-6", "Grid: 6 columns"),
        ("grid-cols-12", "Grid: 12 columns"),
        ("grid-rows-1", "Grid: 1 row"),
        ("grid-rows-2", "Grid: 2 rows"),
        ("grid-rows-3", "Grid: 3 rows"),
        ("col-span-1", "Span 1 column"),
        ("col-span-2", "Span 2 columns"),
        ("col-span-3", "Span 3 columns"),
        ("col-span-full", "Span all columns"),

        // Padding
        ("p-0", "Padding: 0"),
        ("p-1", "Padding: 0.25rem"),
        ("p-2", "Padding: 0.5rem"),
        ("p-3", "Padding: 0.75rem"),
        ("p-4", "Padding: 1rem"),
        ("p-5", "Padding: 1.25rem"),
        ("p-6", "Padding: 1.5rem"),
        ("p-8", "Padding: 2rem"),
        ("p-10", "Padding: 2.5rem"),
        ("p-12", "Padding: 3rem"),
        ("px-0", "Padding X: 0"),
        ("px-1", "Padding X: 0.25rem"),
        ("px-2", "Padding X: 0.5rem"),
        ("px-3", "Padding X: 0.75rem"),
        ("px-4", "Padding X: 1rem"),
        ("px-6", "Padding X: 1.5rem"),
        ("px-8", "Padding X: 2rem"),
        ("py-0", "Padding Y: 0"),
        ("py-1", "Padding Y: 0.25rem"),
        ("py-2", "Padding Y: 0.5rem"),
        ("py-3", "Padding Y: 0.75rem"),
        ("py-4", "Padding Y: 1rem"),
        ("py-6", "Padding Y: 1.5rem"),
        ("py-8", "Padding Y: 2rem"),
        ("pt-4", "Padding top: 1rem"),
        ("pb-4", "Padding bottom: 1rem"),
        ("pl-4", "Padding left: 1rem"),
        ("pr-4", "Padding right: 1rem"),

        // Margin
        ("m-0", "Margin: 0"),
        ("m-1", "Margin: 0.25rem"),
        ("m-2", "Margin: 0.5rem"),
        ("m-3", "Margin: 0.75rem"),
        ("m-4", "Margin: 1rem"),
        ("m-auto", "Margin: auto"),
        ("mx-auto", "Margin X: auto"),
        ("my-auto", "Margin Y: auto"),
        ("mx-4", "Margin X: 1rem"),
        ("my-4", "Margin Y: 1rem"),
        ("mt-0", "Margin top: 0"),
        ("mt-1", "Margin top: 0.25rem"),
        ("mt-2", "Margin top: 0.5rem"),
        ("mt-4", "Margin top: 1rem"),
        ("mt-6", "Margin top: 1.5rem"),
        ("mt-8", "Margin top: 2rem"),
        ("mb-0", "Margin bottom: 0"),
        ("mb-1", "Margin bottom: 0.25rem"),
        ("mb-2", "Margin bottom: 0.5rem"),
        ("mb-4", "Margin bottom: 1rem"),
        ("mb-6", "Margin bottom: 1.5rem"),
        ("mb-8", "Margin bottom: 2rem"),
        ("ml-4", "Margin left: 1rem"),
        ("mr-4", "Margin right: 1rem"),
        ("-mt-1", "Negative margin top"),
        ("-ml-1", "Negative margin left"),

        // Width
        ("w-full", "Width: 100%"),
        ("w-screen", "Width: 100vw"),
        ("w-auto", "Width: auto"),
        ("w-1/2", "Width: 50%"),
        ("w-1/3", "Width: 33.333%"),
        ("w-2/3", "Width: 66.667%"),
        ("w-1/4", "Width: 25%"),
        ("w-3/4", "Width: 75%"),
        ("w-4", "Width: 1rem"),
        ("w-8", "Width: 2rem"),
        ("w-12", "Width: 3rem"),
        ("w-16", "Width: 4rem"),
        ("w-24", "Width: 6rem"),
        ("w-32", "Width: 8rem"),
        ("w-48", "Width: 12rem"),
        ("w-64", "Width: 16rem"),
        ("w-96", "Width: 24rem"),
        ("max-w-xs", "Max width: 20rem"),
        ("max-w-sm", "Max width: 24rem"),
        ("max-w-md", "Max width: 28rem"),
        ("max-w-lg", "Max width: 32rem"),
        ("max-w-xl", "Max width: 36rem"),
        ("max-w-2xl", "Max width: 42rem"),
        ("max-w-full", "Max width: 100%"),
        ("min-w-0", "Min width: 0"),
        ("min-w-full", "Min width: 100%"),

        // Height
        ("h-full", "Height: 100%"),
        ("h-screen", "Height: 100vh"),
        ("h-auto", "Height: auto"),
        ("h-4", "Height: 1rem"),
        ("h-8", "Height: 2rem"),
        ("h-12", "Height: 3rem"),
        ("h-16", "Height: 4rem"),
        ("h-24", "Height: 6rem"),
        ("h-32", "Height: 8rem"),
        ("h-48", "Height: 12rem"),
        ("h-64", "Height: 16rem"),
        ("min-h-0", "Min height: 0"),
        ("min-h-full", "Min height: 100%"),
        ("min-h-screen", "Min height: 100vh"),

        // Typography
        ("text-xs", "Font size: 0.75rem"),
        ("text-sm", "Font size: 0.875rem"),
        ("text-base", "Font size: 1rem"),
        ("text-lg", "Font size: 1.125rem"),
        ("text-xl", "Font size: 1.25rem"),
        ("text-2xl", "Font size: 1.5rem"),
        ("text-3xl", "Font size: 1.875rem"),
        ("text-4xl", "Font size: 2.25rem"),
        ("text-5xl", "Font size: 3rem"),
        ("text-6xl", "Font size: 3.75rem"),
        ("font-thin", "Font weight: 100"),
        ("font-light", "Font weight: 300"),
        ("font-normal", "Font weight: 400"),
        ("font-medium", "Font weight: 500"),
        ("font-semibold", "Font weight: 600"),
        ("font-bold", "Font weight: 700"),
        ("font-extrabold", "Font weight: 800"),
        ("italic", "Font style: italic"),
        ("not-italic", "Font style: normal"),
        ("uppercase", "Text transform: uppercase"),
        ("lowercase", "Text transform: lowercase"),
        ("capitalize", "Text transform: capitalize"),
        ("text-left", "Text align: left"),
        ("text-center", "Text align: center"),
        ("text-right", "Text align: right"),
        ("text-justify", "Text align: justify"),
        ("underline", "Text decoration: underline"),
        ("line-through", "Text decoration: line-through"),
        ("no-underline", "Text decoration: none"),
        ("leading-none", "Line height: 1"),
        ("leading-tight", "Line height: 1.25"),
        ("leading-normal", "Line height: 1.5"),
        ("leading-relaxed", "Line height: 1.625"),
        ("leading-loose", "Line height: 2"),
        ("tracking-tight", "Letter spacing: -0.05em"),
        ("tracking-normal", "Letter spacing: 0"),
        ("tracking-wide", "Letter spacing: 0.025em"),
        ("truncate", "Truncate text with ellipsis"),
        ("whitespace-nowrap", "White space: nowrap"),
        ("break-words", "Word break: break-word"),

        // Colors - Text
        ("text-white", "Text color: white"),
        ("text-black", "Text color: black"),
        ("text-gray-50", "Text color: gray-50"),
        ("text-gray-100", "Text color: gray-100"),
        ("text-gray-200", "Text color: gray-200"),
        ("text-gray-300", "Text color: gray-300"),
        ("text-gray-400", "Text color: gray-400"),
        ("text-gray-500", "Text color: gray-500"),
        ("text-gray-600", "Text color: gray-600"),
        ("text-gray-700", "Text color: gray-700"),
        ("text-gray-800", "Text color: gray-800"),
        ("text-gray-900", "Text color: gray-900"),
        ("text-red-500", "Text color: red-500"),
        ("text-red-600", "Text color: red-600"),
        ("text-blue-500", "Text color: blue-500"),
        ("text-blue-600", "Text color: blue-600"),
        ("text-green-500", "Text color: green-500"),
        ("text-green-600", "Text color: green-600"),
        ("text-indigo-500", "Text color: indigo-500"),
        ("text-indigo-600", "Text color: indigo-600"),
        ("text-purple-500", "Text color: purple-500"),
        ("text-purple-600", "Text color: purple-600"),

        // Colors - Background
        ("bg-white", "Background: white"),
        ("bg-black", "Background: black"),
        ("bg-transparent", "Background: transparent"),
        ("bg-gray-50", "Background: gray-50"),
        ("bg-gray-100", "Background: gray-100"),
        ("bg-gray-200", "Background: gray-200"),
        ("bg-gray-300", "Background: gray-300"),
        ("bg-gray-400", "Background: gray-400"),
        ("bg-gray-500", "Background: gray-500"),
        ("bg-gray-600", "Background: gray-600"),
        ("bg-gray-700", "Background: gray-700"),
        ("bg-gray-800", "Background: gray-800"),
        ("bg-gray-900", "Background: gray-900"),
        ("bg-red-500", "Background: red-500"),
        ("bg-red-600", "Background: red-600"),
        ("bg-blue-500", "Background: blue-500"),
        ("bg-blue-600", "Background: blue-600"),
        ("bg-green-500", "Background: green-500"),
        ("bg-green-600", "Background: green-600"),
        ("bg-indigo-500", "Background: indigo-500"),
        ("bg-indigo-600", "Background: indigo-600"),
        ("bg-purple-500", "Background: purple-500"),
        ("bg-purple-600", "Background: purple-600"),
        ("bg-gradient-to-r", "Gradient: left to right"),
        ("bg-gradient-to-l", "Gradient: right to left"),
        ("bg-gradient-to-t", "Gradient: bottom to top"),
        ("bg-gradient-to-b", "Gradient: top to bottom"),
        ("bg-gradient-to-br", "Gradient: to bottom right"),
        ("bg-gradient-to-bl", "Gradient: to bottom left"),
        ("from-blue-50", "Gradient from: blue-50"),
        ("from-indigo-100", "Gradient from: indigo-100"),
        ("to-blue-100", "Gradient to: blue-100"),
        ("to-indigo-100", "Gradient to: indigo-100"),

        // Border
        ("border", "Border: 1px solid"),
        ("border-0", "Border: none"),
        ("border-2", "Border: 2px solid"),
        ("border-4", "Border: 4px solid"),
        ("border-t", "Border top"),
        ("border-r", "Border right"),
        ("border-b", "Border bottom"),
        ("border-l", "Border left"),
        ("border-gray-200", "Border color: gray-200"),
        ("border-gray-300", "Border color: gray-300"),
        ("border-gray-400", "Border color: gray-400"),
        ("border-red-500", "Border color: red-500"),
        ("border-blue-500", "Border color: blue-500"),
        ("rounded", "Border radius: 0.25rem"),
        ("rounded-sm", "Border radius: 0.125rem"),
        ("rounded-md", "Border radius: 0.375rem"),
        ("rounded-lg", "Border radius: 0.5rem"),
        ("rounded-xl", "Border radius: 0.75rem"),
        ("rounded-2xl", "Border radius: 1rem"),
        ("rounded-3xl", "Border radius: 1.5rem"),
        ("rounded-full", "Border radius: 9999px"),
        ("rounded-none", "Border radius: 0"),

        // Shadow
        ("shadow-sm", "Shadow: small"),
        ("shadow", "Shadow: default"),
        ("shadow-md", "Shadow: medium"),
        ("shadow-lg", "Shadow: large"),
        ("shadow-xl", "Shadow: extra large"),
        ("shadow-2xl", "Shadow: 2x large"),
        ("shadow-none", "Shadow: none"),

        // Opacity
        ("opacity-0", "Opacity: 0"),
        ("opacity-25", "Opacity: 0.25"),
        ("opacity-50", "Opacity: 0.5"),
        ("opacity-75", "Opacity: 0.75"),
        ("opacity-100", "Opacity: 1"),

        // Position
        ("static", "Position: static"),
        ("fixed", "Position: fixed"),
        ("absolute", "Position: absolute"),
        ("relative", "Position: relative"),
        ("sticky", "Position: sticky"),
        ("inset-0", "Top/Right/Bottom/Left: 0"),
        ("top-0", "Top: 0"),
        ("right-0", "Right: 0"),
        ("bottom-0", "Bottom: 0"),
        ("left-0", "Left: 0"),
        ("top-1/2", "Top: 50%"),
        ("left-1/2", "Left: 50%"),
        ("-translate-x-1/2", "Transform: translateX(-50%)"),
        ("-translate-y-1/2", "Transform: translateY(-50%)"),
        ("z-0", "Z-index: 0"),
        ("z-10", "Z-index: 10"),
        ("z-20", "Z-index: 20"),
        ("z-30", "Z-index: 30"),
        ("z-40", "Z-index: 40"),
        ("z-50", "Z-index: 50"),

        // Overflow
        ("overflow-auto", "Overflow: auto"),
        ("overflow-hidden", "Overflow: hidden"),
        ("overflow-visible", "Overflow: visible"),
        ("overflow-scroll", "Overflow: scroll"),
        ("overflow-x-auto", "Overflow X: auto"),
        ("overflow-y-auto", "Overflow Y: auto"),

        // Cursor
        ("cursor-pointer", "Cursor: pointer"),
        ("cursor-default", "Cursor: default"),
        ("cursor-not-allowed", "Cursor: not-allowed"),
        ("cursor-wait", "Cursor: wait"),

        // Transitions
        ("transition", "Transition: all 150ms"),
        ("transition-colors", "Transition: colors 150ms"),
        ("transition-opacity", "Transition: opacity 150ms"),
        ("transition-transform", "Transition: transform 150ms"),
        ("duration-75", "Duration: 75ms"),
        ("duration-100", "Duration: 100ms"),
        ("duration-150", "Duration: 150ms"),
        ("duration-200", "Duration: 200ms"),
        ("duration-300", "Duration: 300ms"),
        ("ease-in", "Timing: ease-in"),
        ("ease-out", "Timing: ease-out"),
        ("ease-in-out", "Timing: ease-in-out"),

        // Transform
        ("scale-0", "Scale: 0"),
        ("scale-50", "Scale: 0.5"),
        ("scale-75", "Scale: 0.75"),
        ("scale-90", "Scale: 0.9"),
        ("scale-95", "Scale: 0.95"),
        ("scale-100", "Scale: 1"),
        ("scale-105", "Scale: 1.05"),
        ("scale-110", "Scale: 1.1"),
        ("rotate-0", "Rotate: 0deg"),
        ("rotate-45", "Rotate: 45deg"),
        ("rotate-90", "Rotate: 90deg"),
        ("rotate-180", "Rotate: 180deg"),

        // Hover states
        ("hover:bg-gray-100", "Hover: bg-gray-100"),
        ("hover:bg-gray-200", "Hover: bg-gray-200"),
        ("hover:bg-blue-600", "Hover: bg-blue-600"),
        ("hover:bg-blue-700", "Hover: bg-blue-700"),
        ("hover:bg-indigo-700", "Hover: bg-indigo-700"),
        ("hover:bg-green-600", "Hover: bg-green-600"),
        ("hover:bg-red-600", "Hover: bg-red-600"),
        ("hover:text-gray-900", "Hover: text-gray-900"),
        ("hover:text-blue-600", "Hover: text-blue-600"),
        ("hover:underline", "Hover: underline"),
        ("hover:scale-105", "Hover: scale 1.05"),
        ("hover:shadow-lg", "Hover: shadow-lg"),
        ("hover:opacity-80", "Hover: opacity 0.8"),

        // Focus states
        ("focus:outline-none", "Focus: no outline"),
        ("focus:ring-2", "Focus: ring 2px"),
        ("focus:ring-blue-500", "Focus: ring blue-500"),
        ("focus:ring-indigo-500", "Focus: ring indigo-500"),
        ("focus:border-blue-500", "Focus: border blue-500"),
        ("focus:bg-gray-100", "Focus: bg-gray-100"),

        // Active states
        ("active:bg-gray-200", "Active: bg-gray-200"),
        ("active:scale-95", "Active: scale 0.95"),

        // Disabled states
        ("disabled:opacity-50", "Disabled: opacity 0.5"),
        ("disabled:cursor-not-allowed", "Disabled: cursor not-allowed"),

        // Responsive prefixes (examples)
        ("sm:flex", "Small screens: flex"),
        ("md:flex", "Medium screens: flex"),
        ("lg:flex", "Large screens: flex"),
        ("xl:flex", "Extra large screens: flex"),
        ("sm:hidden", "Small screens: hidden"),
        ("md:block", "Medium screens: block"),
        ("lg:grid-cols-3", "Large screens: 3 columns"),

        // Dark mode
        ("dark:bg-gray-800", "Dark: bg-gray-800"),
        ("dark:text-white", "Dark: text-white"),
        ("dark:border-gray-700", "Dark: border-gray-700"),

        // Ring
        ("ring-1", "Ring: 1px"),
        ("ring-2", "Ring: 2px"),
        ("ring-4", "Ring: 4px"),
        ("ring-blue-500", "Ring color: blue-500"),
        ("ring-offset-2", "Ring offset: 2px"),

        // Divide
        ("divide-y", "Divide Y"),
        ("divide-x", "Divide X"),
        ("divide-gray-200", "Divide color: gray-200"),

        // Space
        ("space-x-2", "Space between X: 0.5rem"),
        ("space-x-4", "Space between X: 1rem"),
        ("space-y-2", "Space between Y: 0.5rem"),
        ("space-y-4", "Space between Y: 1rem"),

        // Aspect Ratio
        ("aspect-auto", "Aspect ratio: auto"),
        ("aspect-square", "Aspect ratio: 1/1"),
        ("aspect-video", "Aspect ratio: 16/9"),

        // Object Fit
        ("object-contain", "Object fit: contain"),
        ("object-cover", "Object fit: cover"),
        ("object-fill", "Object fit: fill"),
        ("object-center", "Object position: center"),

        // Select
        ("select-none", "User select: none"),
        ("select-text", "User select: text"),
        ("select-all", "User select: all"),

        // Pointer Events
        ("pointer-events-none", "Pointer events: none"),
        ("pointer-events-auto", "Pointer events: auto"),

        // Resize
        ("resize-none", "Resize: none"),
        ("resize", "Resize: both"),
        ("resize-x", "Resize: horizontal"),
        ("resize-y", "Resize: vertical"),

        // Scroll
        ("scroll-smooth", "Scroll behavior: smooth"),
        ("snap-start", "Scroll snap: start"),
        ("snap-center", "Scroll snap: center"),
    ]
});
